let codes = {
    "Andaman and Nicobar": "AN",
    "Andhra Pradesh": "AP",
    "Arunachal Pradesh": "AR",
    Assam: "AS",
    Bihar: "BR",
    Chandigarh: "CH",
    Chhattisgarh: "CT",
    "Daman and Diu": "DD",
    Delhi: "DL",
    "Dadra and Nagar Haveli": "DN",
    Goa: "GA",
    Gujarat: "GJ",
    "Himachal Pradesh": "HP",
    Haryana: "HR",
    Jharkhand: "JH",
    Ladakh: "LD",
    Karnataka: "KA",
    Kerala: "KL",
    Lakshadweep: "LD",
    Maharashtra: "MH",
    Meghalaya: "ML",
    Manipur: "MN",
    "Madhya Pradesh": "MP",
    Mizoram: "MZ",
    Nagaland: "NL",
    Odisha: "OD",
    Punjab: "PB",
    Puducherry: "PY",
    Rajasthan: "RJ",
    Sikkim: "SK",
    Telengana: "TS",
    "Tamil Nadu": "TN",
    Tripura: "TR",
    "Uttar Pradesh": "UP",
    Uttarakhand: "UK",
    "West Bengal": "WB",
    "Jammu and Kashmir": "JK",
};

export default codes;
